name: 'General Docker Build Pipeline Action'
description: 'Invokes an AWS Lambda function that starts and returns the ID of an AWS CodeBuild project and streams the build logs back to Github.'
inputs:
  env-vars-for-codebuild:
    description: 'Comma separated list of environment variables to send to CodeBuild'
    required: false
outputs:
  aws-build-id:
    description: 'The AWS CodeBuild Build ID for this build.'
runs:
  using: 'node12'
  main: 'dist/index.js'
