name: 'General Docker Build Pipeline Action'
description: 'Invokes an AWS Lambda function that starts and returns the ID of an AWS CodeBuild project and streams the build logs back to Github.'
inputs:
  env-vars-for-codebuild:
    description: 'Comma separated list of environment variables to send to CodeBuild'
    required: false
  update-interval:
    description: 'How often the action calls the API for updates'
    required: false
  update-back-off:
    description: 'Base back-off time for the update calls for API if rate-limiting is encountered'
    required: false
  disable-source-override:
    description: 'Set to `true` if you want do disable source repo override'
    required: false
  hide-cloudwatch-logs:
    description: 'Set to `true` to prevent the CloudWatch logs from streaming the output to GitHub'
    required: false
  disable-github-env-vars:
    description: 'Set to `true` if you want do disable github environment variables in codebuild'
    required: false
  gp-ssh-private-key:
    description: 'Deploy key for private repo access - used for fetching private dependencies'
    required: false
outputs:
  aws-build-id:
    description: 'The AWS CodeBuild Build ID for this build.'
runs:
  using: 'node20'
  main: 'dist/index.js'
